### ISSUE TITLE
Individuals: Bug and UI clarity issues with "Toggle" box 

### ISSUE THREAD

**Issue by Ambivalentalfa** [hannamlmv/tseda#13]
The "Toggle" box in the sidebar for the table is unclear in its functionality and exhibits buggy behaviour. When clicked, it modifies the row named "selection" by changing it to a red cross or green check, depending on the value entered. However, the exact logic behind this is ambiguous. 

- If "0" is selected, samples with population ID 0 are marked with a green check, while others are marked with a red cross, seemingly indicating selection. 
- The functionality breaks when any other value besides "0" is entered: selecting any other value than 1 or 0 results in no effect (default 0 is still selected or marked with green boxes). In the case of 1 it has inconsistent behaviour: every other time all samples are marked, or none are.
- If a value other than 0 is entered, the box still displays "0" after submitting, which is misleading as the entered value isn't shown.
- The description "Toggle sample set by index" is unclear and does not explain the feature’s purpose. Why is there even the option to select? It only seems to produce a row of checks and crosses without any effect. 

**Steps to reproduce:**
1. Open the _Individuals_ page.
2. Enter a value in the "Toggle" box (0, 1, or other numbers).
3. Observe the row "selection" changing to a red cross or green check.
4. Note that when values other than 1 are entered, the system behaves inconsistently.

**Expected behaviour:**
- The function of the "Toggle" box should be clearly defined.
- The value entered should be reflected properly in the box and lead to consistent, expected behaviour in the selection process.
- Clarification on the toggle function is needed to explain how it works, as it appears to be tied to selecting samples based on population ID. 
-  If it corresponds to selection of populations it should be named "Select Population" or similar.

**Comment by percyfal** [comment]
Toggle sample set by index (should be by sample name, cf https://github.com/tforest/tseda/issues/22), i.e., change the selected status from false to true or vice versa. The purpose is to include/exclude a sample set from analysis. When I upgraded to the vpages architecture I didn't test this function thoroughly.

**Comment by Ambivalentalfa** [comment]
Solved in #41, however, the selection does not really mean anything as it is not connected to any function for now. 
Also selection should be allowed based on other columns than sample ID. Will add this as a feature request.
