### ISSUE TITLE
Statistics: Throws error if sample set IDs have been modified 

### ISSUE THREAD

**Issue by hannamlmv** [hannamlmv/tseda#17]
If sample set IDs have previously been modified on the "Individuals" page, then both plots on the statistics page show this error: Sample set error. Check sample set indexes.

**Reason for this error:** The plots by default include sample sets 0, 1 and 2. If I reset the sample set ID of population 1 to 4 on the "Individuals" page and then go to the "Statistics" page, there will be a sample set error as sample set ID 1 no longer exists.

**Possible solution:** Let the plots be empty by default or select the first two sample set IDs which are currently available in the data and display those, taking into account any changes that have been made to sample set IDs. This assumes that we want the changes done on the "Individuals" page to propagate to all other pages as they currently do.

**Comment by percyfal** [comment]
Indeed. Ideally the default should be empty, or include all the currently active sample sets.
