### ISSUE TITLE
Indivuduals: Sample set names not in individuals table

### ISSUE THREAD

**Issue by almanilsson** [hannamlmv/tseda#18]
The table doesn’t show the sample set names. It’s hard to identify which set is being referred to. Sample set names should be added to the table. Users have to switch between pages or remember the what samples have which ids.

**Comment by percyfal** [comment]
See https://github.com/tforest/tseda/issues/22, in particular the draft code. The main issue is SampleSetsTable and IndividualsTable are oblivious to oneanother after creation; the solution is to make sample_sets an slot/entry of IndividualsTable and make a sample sets editor that is a view of the current state.
