### ISSUE TITLE
iGNN: All menus in the sidebar are closed as a default.

### ISSUE THREAD

**Issue by hannamlmv** [hannamlmv/tseda#25]
All menus in the sidebar are closed as a default. Whenever anything in a menu is changed, it closes automatically and you have to open it again to keep changing things. 

A change in the menus should not cause the menu to close.

Same problem as #6

**Comment by percyfal** [comment]
The close/open settings are set in `pn.VCard`. I've elaborated both settings, but I do agree that the behaviour you describe is annoying. For settings that the user is unlikely to change, e.g., map settings, this is probably fine, but less so in other cases.

**Comment by Ambivalentalfa** [comment]
Ive added a general feature request for this as it is true for the entirety of the website. #55
