### ISSUE TITLE
Statistics: Unnatural navigation in plots

### ISSUE THREAD

**Issue by hannamlmv** [hannamlmv/tseda#29]
Do we really want to be able to move a round a bar chart by just dragging and dropping, wouldn’t it make more sense to just have a slider to more around horizontally? 

The plot on the "iGNN" page is only "scrollable" in the horizontal direction, which makes more sense.

<img width="933" alt="Skärmavbild 2024-11-15 kl  14 11 25" src="https://github.com/user-attachments/assets/0ceb83fa-95e7-4f1a-b33d-bdf33d2360a1">

**Comment by percyfal** [comment]
Indeed; you can change the "pan" tool to "xpan". Unfortunately this doesn't work for the haplotype GNN plots for some reason (cf https://github.com/tforest/tseda/issues/19)

**Comment by hannamlmv** [comment]
Same as #21

**Comment by hannamlmv** [comment]
closing this as we have many similar issues, collected them in issue #44
