### ISSUE TITLE
Sidebar symbol is misleading and potentially unnecessary

### ISSUE THREAD

**Issue by almanilsson** [hannamlmv/tseda#33]
The dashed symbol in the sidebar, located in the main header of the website, visually suggests that it will display different pages. However, clicking on it opens the settings for the current page, even when no settings exist for that page. See below the _Structure_ page with the sidebar on and off.

It might be more intuitive to remove this version of the sidebar entirely and make the settings static on pages that have them.

The sidebar dashed symbol could be better used to group website sections (e.g., "Analysis", "About Us", "Contact") instead of toggling settings. Or at the very least it should be moved to be part of the contents of that page.

![image](https://github.com/user-attachments/assets/6bd90c0a-6240-4750-82b9-97f95daca139)
![image](https://github.com/user-attachments/assets/040a699c-cbdc-45be-8467-43cbbc268ed5)

**Comment by hannamlmv** [comment]
this was very difficult to do. if the application is rewritten with HTML, design issues like this could be easily fixed
