### ISSUE TITLE
Standardise input behaviour and update mechanism across pages

### ISSUE THREAD

**Issue by almanilsson** [hannamlmv/tseda#35]
Some input boxes update the page as you type, while others only update when pressing Enter. It would be clearer and more efficient to add an "Update" button across all input boxes to prevent unnecessary updates and to provide better control for the user. 

Additionally, the arrows on many input boxes appear to be a remnant from copy-pasting and don't seem to serve a clear purpose.

It would be ideal to establish a consistent standard for these input boxes, possibly through a shared template, that can be imported whenever a specific type of input box is used. Also implementing a standard update mechanism with an "Apply Now" button or similar across all pages to ensure uniformity in how settings are saved and updated. 

This issue relates to #25 and #6.

**Comment by hannamlmv** [comment]
have one refresh button per page

**Comment by almanilsson** [comment]
We have looked through the page and decided that one single way of updating is less intuitive than picking from "automatic" updating and updating prompted by an update button. Thus we wont implement a single standard used on every page.
