### ISSUE TITLE
Warnings in terminal

### ISSUE THREAD

**Issue by hannamlmv** [hannamlmv/tseda#36]
Terminal is covered in the  “WARNING  root: Dropping a patch because it contains a previously known reference (id='p23233'). 

Most of the time this is harmless and usually a result of updating a model on one side of a communications channel while it was being removed on the other end.” warning. 

Perhaps silence it in some config file?

**Comment by percyfal** [comment]
I did look this up at some point (forgot to write down a reference) and I think this is bokeh being overly verbose. You should be able to change logging level in the bokeh interface. AFAICT the messages are harmless though.

**Comment by hannamlmv** [comment]
we decide not to focus on this, as it doesn't affect the user
