### ISSUE TITLE
iGNN: scrolling on page

### ISSUE THREAD

**Issue by almanilsson** [hannamlmv/tseda#37]
Pages do not properly adapt when the browser window is made smaller. A slider to view parts not shown appears in different places across pages. For example, on the _Individuals_ page, the slider only appears when you scroll all the way down to the end of the table, and then you must scroll back up to view the map.

**Comment by hannamlmv** [comment]
the pages adapt horizontally when the window, all pages except Structure. However, if you visit the Structure page and then go back to the other pages, they no longer resize horizontally...

**Comment by hannamlmv** [comment]
Individuals page: horizontal slider appears as a part of the main grey box (as described above)

iGNN page: vertical slider (after GNN haplotype plot has been activated) appears as a part of the main grey box, even though there is also a vertical slider outside of the main grey box.
<img width="216" alt="Skärmavbild 2024-11-20 kl  14 23 43" src="https://github.com/user-attachments/assets/1cce6ea2-7981-44f0-a849-ca50e5848403">


Overall, I only think that we should have sliders OUTSIDE the grey box.

**Comment by hannamlmv** [comment]
> Individuals page: horizontal slider appears as a part of the main grey box (as described above)
> 
> iGNN page: vertical slider (after GNN haplotype plot has been activated) appears as a part of the main grey box, even though there is also a vertical slider outside of the main grey box. <img alt="Skärmavbild 2024-11-20 kl 14 23 43" width="216" src="https://private-user-images.githubusercontent.com/114096089/388109442-1cce6ea2-7981-44f0-a849-ca50e5848403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTUyMjEsIm5iZiI6MTczMjE5NDkyMSwicGF0aCI6Ii8xMTQwOTYwODkvMzg4MTA5NDQyLTFjY2U2ZWEyLTc5ODEtNDRmMC1hODQ5LWNhNTBlNTg0ODQwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxMzE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjg5NmViZWZlMDk1NTUwYzRlYjA0MWUwYjkxNzg0ZTM4MjlkMTI3ZTNjMDlhNGM2YjMwMjkyMzRmM2NlN2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W87UWxY7j6Jw3VCTODx1mWcH6olVOpo9hcFj3Y1HEPU">
> 
> Overall, I only think that we should have sliders OUTSIDE the grey box.

I think this is the only problem in this issue that remains. I tried fixing it, it was hard and made me sad
