### ISSUE TITLE
Sidebar cards being open or closed should be based on user interaction

### ISSUE THREAD

**Issue by Ambivalentalfa** [hannamlmv/tseda#55]
The sidebar option cards currently return to their default state when the page is refreshed, meaning that closed cards will return to being closed even if the user is currently working on changing boxes within that card. We are choosing to make the defaults open so users don't have to keep opening them to change more settings, but preferably it shoudl be based on their interaction.

**Comment by hannamlmv** [comment]
after discussions with Per, let's set most cards as open by default.
