### ISSUE TITLE
Individuals: Map option changes automatically update and close the options dropdown

### ISSUE THREAD

**Issue by Ambivalentalfa** [hannamlmv/tseda#6]
The default state of the individuals page is that _Map options_ is closed. See below:
![image](https://github.com/user-attachments/assets/c3fdf9b1-ffd6-4cfa-b479-872d10d7fd02)

When any change occurs in the _Map options_ then the update is immediately applied and the page refreshes, thus closing the map options. 

A possible solution is that all options sidebars have a "Apply filters" button and that the view only updates when this is clicked.

**Comment by hannamlmv** [comment]
Same problem as #25

**Comment by Ambivalentalfa** [comment]
Ive added a general feature request for this as it is true for the entirety of the website. #55
