### ISSUE TITLE
Add toggle visibility for plots

### ISSUE THREAD

**Issue by almanilsson** [hannamlmv/tseda#60]
Add functionality to temporarily hide or toggle plots on and off, so users can control which plots are visible at any given time.

**Comment by almanilsson** [comment]
This can be easily fixed by just switching to pn.Accordion() instead of pn.Column() on the top level of all page returns!
All listed elements will then be one "card"
![image](https://github.com/user-attachments/assets/b095fba9-0934-4b47-955c-f17dccfa54f0)

**Comment by hannamlmv** [comment]
This should also be done on the trees page when multiple trees are shown, one should be able to hide some of these trees as suggested in [tforest#26](https://github.com/tforest/tseda/issues/26)
